---
- name: Pegando o checksum do wordpress
  uri: url=https://wordpress.org/latest.zip.sha1 return_content=true
  register: wp_checksum

- name: Baixando o Wordpress ultima versão
  get_url: 
      url: https://wordpress.org/latest.zip 
      dest: /tmp/wordpress.zip 
      checksum: "sha1:{{wp_checksum.content}}"

#CONFIGURANDO A INSTALAÇÃO DO WORDPRESS
- name: Instalando ferramentas requeridas
  apt: name={{item}} state=present
  with_items:
          - unzip

- name: Descompactando o Wordpress
  unarchive:
          src: /tmp/wordpress.zip 
          dest: /tmp
          copy: no
          creates: /tmp/wordpress/wp-settings.php

- name: Criando pasta do projeto
  file: dest=/var/www/html/{{wp_domain}}  state=directory

- name: Criando site-avaliable estudo
  file: dest=/etc/nginx/sites-enabled/{{wp_domain}} state=absent

- name: Criando links
  command: ln -s /etc/nginx/sites-available/{{wp_domain}} /etc/nginx/sites-enabled/

- name: Copiando arquivos para o diretorio wordpress
  command: cp -a /tmp/wordpress/. /var/www/html/{{wp_domain}} creates=/var/www/html/{{wp_domain}}/wp-settings.php

- name: Criando a base de dados wordpress
  mysql_db: name={{database_name}} state=present

- name: Criando o usuário wordpress
  mysql_user: name={{database_user}} host={{item}} password={{database_password}} priv={{database_name}}.*:ALL
  with_items:
          - "{{ ansible_hostname }}"
          - 127.0.0.1
          - ::1
          - localhost
  
- name: Banco de dados existe?
  command: mysql - u root {{database_name}} -e "SELECT ID FROM {{database_name}}.wp_users LIMIT 1;"
  register: db_exist
  ignore_errors: true
  changed_when: false

- name: Copiando banco de dados wordpress
  template: src=wp-database.sql dest=/tmp/wp-database.sql
  when: db_exist.rc > 0

- name: Importando banco de dados wordpress
  mysql_db: target=/tmp/wp-database.sql state=import name="{{database_name}}"
  when: db_exist.rc == 1  

- name: Criando a configuração wp-config
  template: src=templates/wp-config.php dest=/var/www/html/{{wp_domain}}/wp-config.php

# tasks file for maneo.wordpress
