---
- name: Pegando o checksum do wordpress
  uri: url=https://wordpress.org/latest.zip.sha1 return_content=true
  register: wp_checksum

- name: Baixando o Wordpress ultima versão
  get_url: 
      url: https://wordpress.org/latest.zip 
      dest: /tmp/wordpress.zip 
      checksum: "sha1:{{wp_checksum.content}}"

#CONFIGURANDO A INSTALAÇÃO DO WORDPRESS
- name: Instalando ferramentas requeridas
  apt: name={{item}} state=present
  with_items:
          - unzip

- name: Descompactando o Wordpress
  unarchive:
          src: /tmp/wordpress.zip 
          dest: /tmp
          copy: no
          creates: /tmp/wordpress/wp-settings.php

- name: Criando pasta do projeto
  file: dest=/var/www/html/estudo  state=directory

- name: Criando site-avaliable estudo
  file: dest=/etc/nginx/sites-enabled/estudo state=absent

- name: Criando links
  command: ln -s /etc/nginx/sites-available/estudo /etc/nginx/sites-enabled/

- name: Copiando arquivos para o diretorio wordpress
  command: cp -a /tmp/wordpress/. /var/www/html/estudo creates=/var/www/html/estudo/wp-settings.php

- name: Criando a base de dados wordpress
  mysql_db: name=wordpress state=present

- name: Criando o usuário wordpress
  mysql_user: name=wordpress host={{item}} password=Sti@2022 priv=wordpress.*:ALL
  with_items:
          - "{{ ansible_hostname }}"
          - 127.0.0.1
          - ::1
          - localhost
  

- name: Criando a configuração wp-config
  template: src=templates/wp-config.php dest=/var/www/html/estudo/wp-config.php

# tasks file for maneo.wordpress
