# tasks file for maneo.common
---
-  name: Atualizando o apt
   apt: update_cache=yes cache_valid_time=3600

- name: Instalando ferramentas requeridas
  apt: name={{item}} state=present
  with_items:
        - unzip
